# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f407e0a799aaedaf2c8592dc61a0df30be37b5d88c729a9d7ffe30ab08acdc9abbf8235d78ef6c8f921f3ff432aa87ac0606f4035fda417fb888b35eaf378db4

test:
  secret_key_base: be583bbe4d72fe2b556b7da886ddedd511c208f72e8ae4acc8c6eb4217f139da0894056b8d06c5a009ebef0feb4bbf6858db504c97df05038a46886fe87f28c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
